### PR TITLE
add E2E test

### PR DESCRIPTION
**Pull request by yshrsmz**
I've added tests for actual network requests(`/v1/gateway/events`, `/v1/gateway/evaluations`).
Other stuff should be covered by unit tests, but feel free to tell me if you need more e2e tests

Also, I'm not planning to add "integration" tests that existed in v1. they use mock, so v2 unit tests(which do not use mock except for MockWebServer) should be more effective.

### CODE REVIEW

**Comment by cre8ivejp** [comment]
Could you also add a test for the `evaluationDetails` interface? 

By the way, the current settings in the admin console will return the evaluation reason `DEFAULT` for all feature flags you created. Just letting you know how to compare the `reason` field in the evaluation details.

https://github.com/ca-dp/bucketeer-android-sdk/blob/v2/bucketeer2/src/main/kotlin/io/bucketeer/sdk/android/internal/model/ReasonType.kt#L6

**Comment by cre8ivejp** [comment]
I have added a rule in this [flag](https://dev.bucketeer.jp/sdke2e/features/feature-android-e2e-string/targeting) to return `value-2` if the user attributes have the `"app_version": "0.0.1"`

Could you please add a test using the `setUserAttributes` interface with the above attribute and check if the `value-2` is returned?

**Comment by yshrsmz** [comment]
Thanks, added test cases

evaluationDetails: [`0456280` (#73)](https://github.com/ca-dp/bucketeer-android-sdk/pull/73/commits/0456280d409132decdd063085c22fd5143b390b0)
setUserAttributes -> fetchEvaluations: [`02daa04` (#73)](https://github.com/ca-dp/bucketeer-android-sdk/pull/73/commits/02daa04e3db55af75de585795f85440aea53353b)

Also, I've added `BKTEvaluation.Reason` enum for better readability. [`fb1ec8a` (#73)](https://github.com/ca-dp/bucketeer-android-sdk/pull/73/commits/fb1ec8a116cdde63353bdac59fb8bc7f42612917)

**Comment by yshrsmz** [comment]
This test cases does not run on CI for now(as it uses API key)

You can run it manually by `./gradlew :bucketeer2:connectedCheck`(you need a real device or an emulator)

**Review by cre8ivejp — APPROVED** [review]
Great!
Thanks!

**Comment by yshrsmz** [comment]
Thanks

**Pull request merged**
